Turn on -Wno-poison-system-directories on clang (#489)
Clang on macos is failing because:
    error: include location '/usr/local/include' is unsafe for cross-compilation [-Werror,-Wpoison-system-directories]
Due to some of the headers coming from brew, let's ignore this warning.